#!/bin/zsh

# Print status
if [[ $# -eq 0 ]]; then
    if [[ -z "$DOTENV_SET" ]]; then
        echo "dotenv is down"
    else
        echo "dotenv is up"
    fi

# Decrypt, set variables
elif [[ "$1" == "up" ]]; then
    read -s "key?Decryption key: "
    echo
    for file in ~/.env/*; do
        if [[ -f "$file" ]]; then
            env_name=$(basename "$file")
            content=$(openssl enc -aes-256-cbc -d -in "$file" -pass pass:"$key" -pbkdf2 -iter 10000 2>/dev/null)
            if [[ $? -ne 0 ]]; then
                echo "Wrong key!"
                return 1
            else
                export "$env_name"="$content"
            fi
        fi
    done
    export DOTENV_SET=1
    echo "~/.env variables set"

# Unset variables
elif [[ "$1" == "down" ]]; then
    for file in ~/.env/*; do
        if [[ -f "$file" ]]; then
            env_name=$(basename "$file")
            unset "$env_name"
        fi
    done
    unset DOTENV_SET
    echo "~/.env variables unset"

# Encrypt
elif [[ "$1" == "enc" ]]; then
    read -s "key?Encryption key: "
    echo
    file=~/.env/"$2"
    plain="$3"
    openssl enc -aes-256-cbc -in "$plain" -pass pass:"$key" -pbkdf2 -iter 10000 -out "$file"
    echo "$2 updated"

# Copy in clipboard
elif [[ "$1" == "clip" ]]; then
    echo "$2" | clip

# Create alias on shell startup
elif [[ "$1" == "init" ]]; then
    echo "alias dotenv='source ${(%):-%N}'"

# Unknown command
else
    echo "Unknown command"
fi

