#!/bin/zsh

alias b='cd ~-'
alias d='tag la'
alias l='tag ls'
alias q='exit'
alias c='clear && tmux clear-history 2>/dev/null'

alias path='echo $PATH | tr : "\n"'
alias ip='ipconfig getifaddr en0'

alias md='glow -altw 120'
alias act='eval $(py-act)'
alias icat='kitty icat'

alias src='source ~/.zshrc'
alias tsrc='tmux source ~/.config/tmux/tmux.conf'

alias gconf='open-config ghostty'
alias vconf='open-config nvim'
alias tconf='open-config tmux'
alias zconf='open-config zsh'

