#!/bin/zsh

# Clear command not found output
command_not_found_handler() {
    print "$PWD"
}

# Fuzzy traverse folders
preexec() {
    local cmdline=$1 # get user's command

    [[ "$cmdline" == *$'\n'* ]] && return           # skip if 2+ lines
    [[ "$cmdline" == *[^[:alnum:]\ .]* ]] && return # skip if there's a symbol

    local words=(${(z)cmdline})   # get command program and args
    (( ${#words} > 0 )) || return # skip empty lines
    local prog=${words[1]}        # get program name

    # If program doesn't exist, use navigation script
    which -- "$prog" > /dev/null 2>&1 || nav "${words[@]}"
}

# Open nvim based on argv
v() {
    if [[ $# == 0 ]]; then
        nvim .
    else
        nvim $@
    fi
}

# Open tmux buffer in editor
edit-tmux-pane() {
    tmux capture-pane -p -S - |
        tr "" ">" |
        tail -n +2 |
        $EDITOR +'normal G{}b$' -R
}

# Cd in recursive fuzzy find
ss() {
    local dir="."
    [[ $# != 0 ]] && dir="$(nav -- "$@")"
    cd "$(find $dir -type d -not -path '*/.*' 2>/dev/null |
          fzf --preview 'echo -e "\033[1;31m{}\033[0m\n"; tag la {}')"
}

# Open config folder
open-config() {
    pushd ~/.config > /dev/null
    cd "$1"
    $EDITOR .
    popd > /dev/null
}

# Show tree of git added files
gitree() {
    (   cd "${1:-.}"
        git ls-tree -r --name-only HEAD;
        git diff --cached --name-only --relative
    ) | sort -u \
      | tree -a --fromfile
}

# SSH keys
ssh-load() {
    [[ -z "$1" ]] && return 1
    local tmpfile=$(mktemp -t ssh-key.XXXXXX)
    print "$1" > "$tmpfile"
    chmod 600 "$tmpfile"
    ssh-add "$tmpfile"
    rm "$tmpfile"
}

# Make PDF from TeX
makepdf() {
    pdflatex main.tex > /dev/null
    pdflatex main.tex > /dev/null
    rm -rf *.aux *.log *.out *.toc *.fls _minted
}

py-act() {
    print "command -v deactivate && deactivate;"
    print "source (.||_)venv/bin/activate 2>/dev/null && echo activate;"
}

..() {
    b=${1:-1}
    res=""
    [[ -n "$1" ]] && print "0: $(pwd)"
    [[ 1 -gt $b ]] && return
    for n in $(seq $b); do
        res="../$res"
        [[ -n "$1" ]] && print "$n: $(cd $res; pwd)"
    done
    cd "$res"
}

